[build]
command = "npm run build"
output_directory = "out"
base_directory = ""

[build.environment]
NODE_VERSION = "18"

[functions]
# 禁用 Cloudflare Functions
directory = ""

[site]
bucket = "out"
entry-point = "" # 静态站点不需要入口点 